// resources/js/App.tsx
import React, { createContext, useContext, useState, useEffect } from 'react';
import { BrowserRouter, Routes, Route, Navigate, Link, useNavigate, useLocation } from 'react-router-dom';
import axios from 'axios';
import { 
  LayoutDashboard, Users, Car, FileText, FileSpreadsheet, 
  Settings, Database, CreditCard, LogOut, Sun, Moon, Menu, X, CheckSquare
} from 'lucide-react';

// Create contexts
const AuthContext = createContext<any>(null);
const SettingsContext = createContext<any>(null);

export const useAuth = () => useContext(AuthContext);
export const useSettings = () => useContext(SettingsContext);

// Layout Component
const DashboardLayout = ({ children, darkMode, setDarkMode }: { children: React.ReactNode, darkMode: boolean, setDarkMode: (v: boolean) => void }) => {
  const { logout, user } = useAuth();
  const { settings } = useSettings();
  const navigate = useNavigate();
  const location = useLocation();
  const [sidebarOpen, setSidebarOpen] = useState(true);

  const menuItems = [
    { name: 'Dashboard', path: '/dashboard', icon: LayoutDashboard },
    { name: 'Job Cards', path: '/jobcards', icon: CheckSquare },
    { name: 'Quotations', path: '/quotations', icon: FileSpreadsheet },
    { name: 'Invoice Builder', path: '/invoices', icon: FileText },
    { name: 'Invoices & Payments', path: '/payments', icon: CreditCard },
    { name: 'Customer DB', path: '/customers', icon: Users },
    { name: 'Vehicle DB', path: '/vehicles', icon: Car },
    { name: 'Workshop Settings', path: '/settings', icon: Settings },
    { name: 'Backup & Restore', path: '/backup', icon: Database },
  ];

  return (
    <div className={`min-h-screen flex ${darkMode ? 'bg-slate-950 text-slate-100' : 'bg-slate-50 text-slate-800'}`}>
      {/* Sidebar */}
      <aside 
        className={`fixed inset-y-0 left-0 z-30 w-64 border-r transition-transform duration-300 transform lg:translate-x-0 lg:static lg:inset-0 noprint
          ${sidebarOpen ? 'translate-x-0' : '-translate-x-full'}
          ${darkMode ? 'bg-slate-900 border-slate-800' : 'bg-white border-slate-200'}`}
      >
        <div className="h-16 flex items-center justify-between px-6 border-b border-inherit">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-red-600 flex items-center justify-center font-bold text-white">TC</div>
            <div>
              <h1 className="font-bold text-sm leading-tight">TRUST CARE</h1>
              <span className="text-[10px] text-red-500 font-semibold tracking-wider block -mt-0.5">WORKSHOP</span>
            </div>
          </div>
          <button onClick={() => setSidebarOpen(false)} className="lg:hidden text-inherit">
            <X size={20} />
          </button>
        </div>

        <nav className="p-4 space-y-1 overflow-y-auto" style={{ height: 'calc(100vh - 12rem)' }}>
          {menuItems.map((item) => {
            const Icon = item.icon;
            const isActive = location.pathname === item.path;
            return (
              <Link
                key={item.name}
                to={item.path}
                className={`flex items-center gap-3 px-4 py-3 rounded-lg text-sm font-medium transition-all
                  ${isActive 
                    ? 'bg-red-600 text-white shadow-lg shadow-red-600/20' 
                    : darkMode 
                      ? 'hover:bg-slate-800 text-slate-400 hover:text-slate-100' 
                      : 'hover:bg-slate-100 text-slate-600 hover:text-slate-950'}`}
              >
                <Icon size={18} />
                <span>{item.name}</span>
              </Link>
            );
          })}
        </nav>

        <div className="absolute bottom-0 w-full p-4 border-t border-inherit">
          <div className="flex items-center justify-between mb-4">
            <span className="text-xs text-slate-500">Logged in as: <b className="text-slate-400">{user?.username}</b></span>
            <button 
              onClick={() => setDarkMode(!darkMode)}
              className={`p-1.5 rounded-lg border border-inherit text-inherit`}
            >
              {darkMode ? <Sun size={14} /> : <Moon size={14} />}
            </button>
          </div>
          <button
            onClick={() => { logout(); navigate('/login'); }}
            className="flex items-center justify-center gap-2 w-full px-4 py-2.5 rounded-lg bg-slate-800 hover:bg-red-600 hover:text-white text-slate-300 text-xs font-semibold transition-all border border-slate-700"
          >
            <LogOut size={14} />
            <span>Logout</span>
          </button>
        </div>
      </aside>

      {/* Main Content Area */}
      <div className="flex-1 flex flex-col min-w-0 overflow-hidden">
        {/* Top Navbar */}
        <header className={`h-16 flex items-center justify-between px-6 border-b noprint
          ${darkMode ? 'bg-slate-900 border-slate-800' : 'bg-white border-slate-200'}`}
        >
          <div className="flex items-center gap-4">
            <button onClick={() => setSidebarOpen(!sidebarOpen)} className="text-inherit">
              <Menu size={20} />
            </button>
            <div>
              <h2 className="font-bold text-lg leading-tight uppercase">
                {menuItems.find(item => item.path === location.pathname)?.name || 'Trust Care'}
              </h2>
            </div>
          </div>
          <div className="flex items-center gap-4">
            {settings?.logo && (
              <img src={settings.logo} alt="Logo" className="h-9 object-contain" />
            )}
            <span className="text-sm font-semibold hidden md:inline-block">
              {settings?.workshop_name || 'TRUST CARE WORKSHOP'}
            </span>
          </div>
        </header>

        {/* Dynamic Page Content */}
        <main className="flex-1 overflow-auto p-6 md:p-8">
          <div className="max-w-7xl mx-auto">
            {children}
          </div>
        </main>
      </div>
    </div>
  );
};

// Protected Route check wrapper
const ProtectedRoute = ({ children, darkMode, setDarkMode }: { children: React.ReactNode, darkMode: boolean, setDarkMode: (v: boolean) => void }) => {
  const { token } = useAuth();
  if (!token) return <Navigate to="/login" replace />;
  return <DashboardLayout darkMode={darkMode} setDarkMode={setDarkMode}>{children}</DashboardLayout>;
};

// Main Routing App wrapper
export default function App() {
  const [user, setUser] = useState<any>(null);
  const [token, setToken] = useState<string | null>(localStorage.getItem('token'));
  const [settings, setSettings] = useState<any>(null);
  const [darkMode, setDarkMode] = useState<boolean>(localStorage.getItem('theme') !== 'light');
  const [loading, setLoading] = useState(true);

  // Configure Axios default authorization token
  if (token) {
    axios.defaults.headers.common['Authorization'] = `Bearer ${token}`;
  } else {
    delete axios.defaults.headers.common['Authorization'];
  }

  // Manage application theme
  useEffect(() => {
    if (darkMode) {
      document.documentElement.classList.add('dark');
      localStorage.setItem('theme', 'dark');
    } else {
      document.documentElement.classList.remove('dark');
      localStorage.setItem('theme', 'light');
    }
  }, [darkMode]);

  // Load user status on startup
  useEffect(() => {
    const fetchMeAndSettings = async () => {
      // First load public settings
      try {
        const setRes = await axios.get('/api/settings');
        setSettings(setRes.data);
      } catch (err) {
        console.error('Error fetching settings', err);
      }

      if (token) {
        try {
          const authRes = await axios.get('/api/auth/me');
          setUser(authRes.data);
        } catch (err) {
          console.error('Invalid token, logging out', err);
          logout();
        }
      }
      setLoading(false);
    };
    fetchMeAndSettings();
  }, [token]);

  const login = (newToken: string, newUser: any) => {
    localStorage.setItem('token', newToken);
    setToken(newToken);
    setUser(newUser);
  };

  const logout = () => {
    localStorage.removeItem('token');
    setToken(null);
    setUser(null);
  };

  const refreshSettings = async () => {
    try {
      const setRes = await axios.get('/api/settings');
      setSettings(setRes.data);
    } catch (err) {
      console.error(err);
    }
  };

  const updateSettings = async (newData: any) => {
    try {
      const res = await axios.post('/api/settings', newData);
      setSettings(res.data.settings);
      return true;
    } catch (err) {
      console.error(err);
      return false;
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-slate-950 flex flex-col items-center justify-center text-white">
        <div className="w-12 h-12 rounded-full border-4 border-red-600 border-t-transparent animate-spin mb-4"></div>
        <p className="text-sm font-semibold tracking-widest text-slate-400">LOADING TRUST CARE SYSTEM...</p>
      </div>
    );
  }

  // Lazy loaded Pages (we'll implement them below)
  // Let's create route imports. We will write placeholder or basic imports, but actually we will create the page files directly.
  return (
    <AuthContext.Provider value={{ user, token, login, logout }}>
      <SettingsContext.Provider value={{ settings, refreshSettings, updateSettings }}>
        <BrowserRouter>
          <Routes>
            <Route path="/login" element={!token ? <LoginPage /> : <Navigate to="/dashboard" />} />
            <Route path="/register" element={!token ? <RegisterPage /> : <Navigate to="/dashboard" />} />
            
            <Route path="/dashboard" element={<ProtectedRoute darkMode={darkMode} setDarkMode={setDarkMode}><DashboardPage /></ProtectedRoute>} />
            <Route path="/jobcards" element={<ProtectedRoute darkMode={darkMode} setDarkMode={setDarkMode}><JobCardsPage /></ProtectedRoute>} />
            <Route path="/quotations" element={<ProtectedRoute darkMode={darkMode} setDarkMode={setDarkMode}><QuotationsPage /></ProtectedRoute>} />
            <Route path="/invoices" element={<ProtectedRoute darkMode={darkMode} setDarkMode={setDarkMode}><InvoicesPage /></ProtectedRoute>} />
            <Route path="/payments" element={<ProtectedRoute darkMode={darkMode} setDarkMode={setDarkMode}><PaymentsPage /></ProtectedRoute>} />
            <Route path="/customers" element={<ProtectedRoute darkMode={darkMode} setDarkMode={setDarkMode}><CustomersPage /></ProtectedRoute>} />
            <Route path="/vehicles" element={<ProtectedRoute darkMode={darkMode} setDarkMode={setDarkMode}><VehiclesPage /></ProtectedRoute>} />
            <Route path="/settings" element={<ProtectedRoute darkMode={darkMode} setDarkMode={setDarkMode}><SettingsPage /></ProtectedRoute>} />
            <Route path="/backup" element={<ProtectedRoute darkMode={darkMode} setDarkMode={setDarkMode}><BackupPage /></ProtectedRoute>} />
            
            <Route path="*" element={<Navigate to="/dashboard" replace />} />
          </Routes>
        </BrowserRouter>
      </SettingsContext.Provider>
    </AuthContext.Provider>
  );
}

// Temporary layout route stub mappings to actual page classes we are creating in pages/
import LoginPage from './pages/Login';
import RegisterPage from './pages/Register';
import DashboardPage from './pages/Dashboard';
import JobCardsPage from './pages/JobCards';
import QuotationsPage from './pages/Quotations';
import InvoicesPage from './pages/Invoices';
import PaymentsPage from './pages/Payments';
import CustomersPage from './pages/Customers';
import VehiclesPage from './pages/Vehicles';
import SettingsPage from './pages/SettingsPage';
import BackupPage from './pages/BackupPage';

// resources/js/App.vue
<script setup lang="ts">
import { ref, onMounted, computed, watch } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { useAuthStore } from './stores/auth'
import { useSettingsStore } from './stores/settings'
import { 
  LayoutDashboard, Users, Car, FileText, Settings, Database, 
  CreditCard, LogOut, Sun, Moon, Menu, X, CheckSquare, Shield,
  Package, FileBarChart
} from 'lucide-vue-next' // Lucide icons for Vue

const authStore = useAuthStore()
const settingsStore = useSettingsStore()
const router = useRouter()
const route = useRoute()

// Theme State
const darkMode = ref(localStorage.getItem('theme') !== 'light')
const sidebarOpen = ref(true)

// Toggle Theme
const toggleTheme = () => {
  darkMode.value = !darkMode.value
  if (darkMode.value) {
    document.documentElement.classList.add('dark')
    document.documentElement.setAttribute('data-bs-theme', 'dark')
    localStorage.setItem('theme', 'dark')
  } else {
    document.documentElement.classList.remove('dark')
    document.documentElement.setAttribute('data-bs-theme', 'light')
    localStorage.setItem('theme', 'light')
  }
}

// Sync theme class on load
onMounted(() => {
  if (darkMode.value) {
    document.documentElement.classList.add('dark')
    document.documentElement.setAttribute('data-bs-theme', 'dark')
  } else {
    document.documentElement.classList.remove('dark')
    document.documentElement.setAttribute('data-bs-theme', 'light')
  }
  
  if (authStore.isAuthenticated) {
    settingsStore.fetchSettings()
  }
})

// Check if current route is a guest page (Login/Register)
const isGuestPage = computed(() => route.meta.guest === true)

const handleLogout = async () => {
  await authStore.logout()
  router.push('/login')
}

// Sidebar Menu Items filtered by active user role permissions
const menuItems = computed(() => {
  const allItems = [
    { name: 'Dashboard', path: '/dashboard', icon: LayoutDashboard, roles: ['admin', 'advisor', 'manager'] },
    { name: 'Job Cards', path: '/jobcards', icon: CheckSquare, roles: ['admin', 'advisor'] },
    { name: 'Invoices', path: '/invoices', icon: FileText, roles: ['admin', 'advisor'] },
    { name: 'Payments', path: '/payments', icon: CreditCard, roles: ['admin', 'advisor'] },
    { name: 'Inventory', path: '/inventory', icon: Package, roles: ['admin', 'manager'] },
    { name: 'Customer DB', path: '/customers', icon: Users, roles: ['admin', 'advisor'] },
    { name: 'Vehicle DB', path: '/vehicles', icon: Car, roles: ['admin', 'advisor'] },
    { name: 'Reports', path: '/reports', icon: FileBarChart, roles: ['admin'] },
    { name: 'Settings', path: '/settings', icon: Settings, roles: ['admin'] },
  ]
  
  if (!authStore.user) return []
  return allItems.filter(item => item.roles.includes(authStore.user.role))
})

// Auto close mobile sidebar on route change
watch(() => route.path, () => {
  if (window.innerWidth < 992) {
    sidebarOpen.value = false
  }
})

// Fetch settings when user becomes authenticated
watch(() => authStore.isAuthenticated, (newVal) => {
  if (newVal) {
    settingsStore.fetchSettings()
  }
})

const handleNavClick = () => {
  if (window.innerWidth < 992) {
    sidebarOpen.value = false
  }
}
</script>

<template>
  <div :class="{'dark-theme': darkMode, 'light-theme': !darkMode}">
    <!-- Guest Layout -->
    <div v-if="isGuestPage" class="guest-container">
      <router-view />
    </div>

    <!-- Main Workspace Layout -->
    <div v-else class="app-layout">
      <!-- Sidebar -->
      <aside class="sidebar noprint" :class="{'sidebar-closed': !sidebarOpen}">
        <div class="sidebar-header d-flex align-items-center justify-content-between">
          <img src="/logo.png" alt="Trust Care" class="sidebar-logo-img" style="max-height: 42px; max-width: 175px; object-fit: contain;" />
          <button class="close-sidebar-btn" @click="sidebarOpen = false">
            <X :size="18" />
          </button>
        </div>

        <nav class="sidebar-nav">
          <router-link 
            v-for="item in menuItems" 
            :key="item.name" 
            :to="item.path"
            class="nav-item"
            active-class="nav-item-active"
            @click="handleNavClick"
          >
            <component :is="item.icon" :size="16" />
            <span>{{ item.name }}</span>
          </router-link>
        </nav>

        <div class="sidebar-footer">
          <div class="user-meta">
            <div class="username">{{ authStore.user?.name || 'User' }}</div>
            <div class="role-badge">{{ authStore.user?.role }}</div>
          </div>
          <div class="footer-actions">
            <button class="btn-theme" @click="toggleTheme" title="Toggle Theme">
              <Sun v-if="darkMode" :size="14" />
              <Moon v-else :size="14" />
            </button>
            <button class="btn-logout" @click="handleLogout" title="Logout">
              <LogOut :size="14" />
              <span>Logout</span>
            </button>
          </div>
        </div>
      </aside>

      <!-- Main Section -->
      <div class="main-wrapper">
        <!-- Top Navbar -->
        <header class="topbar noprint">
          <button class="menu-toggle-btn" @click="sidebarOpen = !sidebarOpen">
            <Menu :size="20" />
          </button>
          
          <div class="topbar-right">
            <span class="workshop-heading">{{ settingsStore.settings?.workshop_name || 'TRUST CARE WORKSHOP' }}</span>
          </div>
        </header>

        <!-- View content -->
        <main class="page-content">
          <div class="container-fluid py-4">
            <router-view />
          </div>
        </main>
      </div>
    </div>
  </div>
</template>

<style>
/* Global CSS variables matching Brand Colors */
:root {
  --primary-color: #d71920; /* Trust Care Red */
  --bg-light: #f8f9fa;
  --bg-dark: #111111;
  --border-light: #dee2e6;
  
  --font-family: 'Inter', sans-serif;
}

body {
  font-family: var(--font-family);
  margin: 0;
  padding: 0;
}

/* Light Theme */
.light-theme {
  --bg-body: #f8f9fa;
  --bg-body-rgb: 248, 249, 250;
  --bg-sidebar: #ffffff;
  --bg-card: #ffffff;
  --bg-card-rgb: 255, 255, 255;
  --text-main: #111111;
  --text-muted: #6c757d;
  --border-color: #dee2e6;
  --sidebar-active: #d71920;
  --sidebar-text: #495057;
  --sidebar-active-text: #ffffff;
}

/* Dark Theme */
.dark-theme {
  --bg-body: #0a0a0a;
  --bg-body-rgb: 10, 10, 10;
  --bg-sidebar: #121212;
  --bg-card: #1e1e1e;
  --bg-card-rgb: 30, 30, 30;
  --text-main: #f8f9fa;
  --text-muted: #adb5bd;
  --border-color: #2c2c2c;
  --sidebar-active: #d71920;
  --sidebar-text: #adb5bd;
  --sidebar-active-text: #ffffff;
}

/* Layout Framework */
.app-layout {
  display: flex;
  min-h: 100vh;
  background-color: var(--bg-body);
  color: var(--text-main);
  transition: background-color 0.2s ease, color 0.2s ease;
}

.guest-container {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #111111;
}

/* Sidebar Styling */
.sidebar {
  width: 250px;
  background-color: var(--bg-sidebar);
  border-right: 1px solid var(--border-color);
  display: flex;
  flex-direction: column;
  height: 100vh;
  position: sticky;
  top: 0;
  z-index: 1000;
  transition: transform 0.3s ease, width 0.3s ease, background-color 0.2s ease;
}

.sidebar-closed {
  width: 0;
  transform: translateX(-250px);
  overflow: hidden;
}

.sidebar-header {
  height: 60px;
  display: flex;
  align-items: center;
  padding: 0 20px;
  border-bottom: 1px solid var(--border-color);
  position: relative;
}

.logo-box {
  width: 32px;
  height: 32px;
  border-radius: 6px;
  background-color: var(--primary-color);
  color: #fff;
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: 800;
  font-size: 14px;
}

.logo-text {
  margin-left: 10px;
}

.logo-text h5 {
  margin: 0;
  font-size: 14px;
  font-weight: 700;
  line-height: 1.1;
}

.logo-text span {
  font-size: 9px;
  color: var(--primary-color);
  font-weight: 700;
  letter-spacing: 0.5px;
}

.close-sidebar-btn {
  display: none;
  background: none;
  border: none;
  color: var(--text-main);
  position: absolute;
  right: 15px;
}

.sidebar-nav {
  flex: 1;
  padding: 15px 10px;
  overflow-y: auto;
}

.nav-item {
  display: flex;
  align-items: center;
  padding: 10px 15px;
  margin-bottom: 4px;
  border-radius: 8px;
  color: var(--sidebar-text);
  text-decoration: none;
  font-size: 13px;
  font-weight: 500;
  gap: 10px;
  transition: all 0.2s ease;
}

.nav-item:hover {
  background-color: rgba(215, 25, 32, 0.08);
  color: var(--primary-color);
}

.nav-item-active {
  background-color: var(--sidebar-active) !important;
  color: var(--sidebar-active-text) !important;
  box-shadow: 0 4px 12px rgba(215, 25, 32, 0.2);
}

.sidebar-footer {
  padding: 15px;
  border-top: 1px solid var(--border-color);
  background-color: rgba(0, 0, 0, 0.02);
}

.user-meta {
  margin-bottom: 12px;
}

.username {
  font-size: 13px;
  font-weight: 600;
}

.role-badge {
  display: inline-block;
  font-size: 9px;
  padding: 2px 6px;
  background-color: rgba(215, 25, 32, 0.1);
  color: var(--primary-color);
  border-radius: 4px;
  font-weight: 700;
  text-transform: uppercase;
  margin-top: 2px;
}

.footer-actions {
  display: flex;
  gap: 8px;
}

.btn-theme {
  width: 32px;
  height: 32px;
  border-radius: 6px;
  border: 1px solid var(--border-color);
  background-color: var(--bg-sidebar);
  color: var(--text-main);
  display: flex;
  align-items: center;
  justify-content: center;
}

.btn-logout {
  flex: 1;
  height: 32px;
  border-radius: 6px;
  border: 1px solid var(--border-color);
  background-color: var(--bg-sidebar);
  color: var(--text-muted);
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 6px;
  font-size: 12px;
  font-weight: 600;
}

.btn-logout:hover {
  background-color: var(--primary-color);
  color: #fff;
  border-color: var(--primary-color);
}

/* Main Section Styling */
.main-wrapper {
  flex: 1;
  display: flex;
  flex-direction: column;
  min-width: 0;
  min-height: 100vh;
}

.topbar {
  height: 60px;
  background-color: var(--bg-sidebar);
  border-bottom: 1px solid var(--border-color);
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 20px;
  transition: background-color 0.2s ease;
}

.menu-toggle-btn {
  background: none;
  border: none;
  color: var(--text-main);
  cursor: pointer;
}

.workshop-heading {
  font-size: 14px;
  font-weight: 700;
}

.page-content {
  flex: 1;
  overflow-y: auto;
}

/* Card overrides for Bootstrap to inherit variables */
.card {
  background-color: var(--bg-card) !important;
  border-color: var(--border-color) !important;
  color: var(--text-main) !important;
  border-radius: 12px !important;
  box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05) !important;
  transition: background-color 0.2s ease, border-color 0.2s ease;
}

.card-header {
  border-bottom-color: var(--border-color) !important;
  background-color: rgba(0,0,0,0.02) !important;
}

/* Fix Bootstrap background utility classes in dark mode */
.bg-body {
  background-color: var(--bg-body) !important;
}
.bg-body.bg-opacity-50 {
  background-color: rgba(var(--bg-body-rgb), 0.5) !important;
}
.bg-body.bg-opacity-25 {
  background-color: rgba(var(--bg-body-rgb), 0.25) !important;
}
.bg-card {
  background-color: var(--bg-card) !important;
}
.bg-glass {
  background-color: var(--bg-card) !important;
  backdrop-filter: blur(10px) !important;
}

/* Global border overrides for theme cohesion */
.border, .border-top, .border-bottom, .border-start, .border-end, .border-secondary {
  border-color: var(--border-color) !important;
}

.table {
  color: var(--text-main) !important;
  border-color: var(--border-color) !important;
  background-color: transparent !important;
}

.table tr, .table td, .table th {
  background-color: transparent !important;
}

.table th {
  background-color: rgba(0,0,0,0.04) !important;
  border-bottom-color: var(--border-color) !important;
  font-weight: 700;
}

.dark-theme .table th {
  background-color: rgba(255,255,255,0.04) !important;
}

.table td {
  border-bottom-color: var(--border-color) !important;
  vertical-align: middle;
}

.form-control, .form-select {
  background-color: var(--bg-body) !important;
  border-color: var(--border-color) !important;
  color: var(--text-main) !important;
}

.form-control:focus, .form-select:focus {
  border-color: var(--primary-color) !important;
  box-shadow: 0 0 0 0.25rem rgba(215, 25, 32, 0.15) !important;
}

.dark-theme .text-muted,
.dark-theme .text-secondary,
.light-theme .text-muted,
.light-theme .text-secondary {
  color: var(--text-muted) !important;
}

.dark-theme .form-control::placeholder,
.dark-theme textarea::placeholder,
.light-theme .form-control::placeholder,
.light-theme textarea::placeholder {
  color: var(--text-muted) !important;
  opacity: 0.6 !important;
}

/* Global Autocomplete Suggestion Dropdowns */
.suggestions-dropdown {
  background-color: var(--bg-card) !important;
  border: 1px solid var(--border-color) !important;
  color: var(--text-main) !important;
  max-height: 200px;
  overflow-y: auto;
  z-index: 1050;
  border-radius: 8px;
  box-shadow: 0 10px 15px -3px rgba(0,0,0,0.3), 0 4px 6px -2px rgba(0,0,0,0.3);
}

.suggestion-row {
  padding: 8px 12px;
  cursor: pointer;
  border-bottom: 1px solid var(--border-color);
  transition: background-color 0.15s, color 0.15s;
  text-align: left;
}

.suggestion-row:last-child {
  border-bottom: none;
}

.suggestion-row:hover, .suggestion-row.active {
  background-color: var(--primary-color) !important;
  color: #ffffff !important;
}

/* Print CSS overrides */
@media print {
  .noprint {
    display: none !important;
  }
  .app-layout {
    display: block !important;
    background: #fff !important;
    color: #000 !important;
  }
  .main-wrapper {
    min-height: auto !important;
  }
}

/* Mobile Screen */
@media (max-width: 991.98px) {
  .close-sidebar-btn {
    display: block;
  }
  .sidebar {
    position: fixed;
    height: 100vh;
    left: 0;
    transform: translateX(0);
    z-index: 1050;
  }
  .sidebar-closed {
    transform: translateX(-100%);
  }
}
</style>
