// resources/js/views/Payments.vue
<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import axios from 'axios'
import { 
  CreditCard, Search, PlusCircle, Check, 
  User, DollarSign, Wallet, FileText, X
} from 'lucide-vue-next'

const invoices = ref<any[]>([])
const searchQuery = ref('')
const loading = ref(false)

const showPaymentModal = ref(false)
const selectedInvoice = ref<any | null>(null)
const formPayment = ref({
  amount: 0,
  payment_mode: 'Cash'
})

const fetchPendingInvoices = async () => {
  loading.value = true
  try {
    // Fetch all invoices. We will filter pending/partially paid in the UI or let user see all
    const res = await axios.get('/api/invoices')
    invoices.value = res.data
  } catch (err) {
    console.error('Failed to load invoices', err)
  } finally {
    loading.value = false
  }
}

// Filter invoices that have an outstanding balance due
const outstandingInvoices = computed(() => {
  const query = searchQuery.value.toLowerCase()
  return invoices.value.filter(inv => {
    const isPending = inv.payment_status === 'Pending' || inv.payment_status === 'Partially Paid'
    const matchesSearch = inv.invoice_no.toLowerCase().includes(query) || 
                          inv.vehicle_reg_no.toLowerCase().includes(query) ||
                          inv.customer?.name.toLowerCase().includes(query) ||
                          inv.customer?.mobile.toLowerCase().includes(query)
    return isPending && matchesSearch
  })
})

const openPaymentModal = (invoice: any) => {
  selectedInvoice.value = invoice
  formPayment.value = {
    amount: parseFloat(invoice.balance_due),
    payment_mode: 'Cash'
  }
  showPaymentModal.value = true
}

const savePayment = async () => {
  if (!selectedInvoice.value) return
  if (formPayment.value.amount <= 0) {
    alert('Please enter a valid payment amount.')
    return
  }
  if (formPayment.value.amount > parseFloat(selectedInvoice.value.balance_due)) {
    alert('Payment amount cannot exceed the balance due.')
    return
  }
  
  try {
    await axios.post(`/api/invoices/${selectedInvoice.value.id}/payment`, formPayment.value)
    showPaymentModal.value = false
    fetchPendingInvoices()
  } catch (err: any) {
    alert(err.response?.data?.error || 'Failed to record payment.')
  }
}

onMounted(() => {
  fetchPendingInvoices()
})

const formatCurrency = (val: any) => {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR'
  }).format(parseFloat(val))
}
</script>

<template>
  <div class="payments-container animate-fade-in">
    <!-- Header -->
    <div class="d-flex justify-content-between align-items-center mb-4">
      <div>
        <h3 class="fw-bold mb-1">Accounts Outstanding Ledger</h3>
        <p class="text-muted small mb-0">Record customer cash/UPI collections, audit balances, and update receipts.</p>
      </div>
    </div>

    <!-- Stats summary bar -->
    <div class="row g-3 mb-4">
      <div class="col-12 col-md-4">
        <div class="card border-0 shadow-sm bg-glass p-3">
          <div class="d-flex justify-content-between align-items-center">
            <div>
              <span class="text-muted text-uppercase small font-bold">Total Accounts Receivable</span>
              <h3 class="fw-bold text-danger mt-1 mb-0">
                {{ formatCurrency(invoices.reduce((acc, inv) => acc + (inv.payment_status !== 'Paid' ? parseFloat(inv.balance_due) : 0), 0)) }}
              </h3>
            </div>
            <div class="p-3 bg-danger bg-opacity-10 text-danger rounded-3">
              <Wallet :size="20" />
            </div>
          </div>
        </div>
      </div>
      <div class="col-12 col-md-4">
        <div class="card border-0 shadow-sm bg-glass p-3">
          <div class="d-flex justify-content-between align-items-center">
            <div>
              <span class="text-muted text-uppercase small font-bold">Unpaid Vehicles</span>
              <h3 class="fw-bold text-warning mt-1 mb-0">
                {{ invoices.filter(inv => inv.payment_status !== 'Paid').length }}
              </h3>
            </div>
            <div class="p-3 bg-warning bg-opacity-10 text-warning rounded-3">
              <CreditCard :size="20" />
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Outstanding Invoices List -->
    <div class="card border-0 shadow-sm bg-glass">
      <div class="card-header border-0 bg-transparent pt-4 px-4 pb-0">
        <div class="row g-3 align-items-center justify-content-between">
          <div class="col-12 col-md-6">
            <h5 class="fw-bold m-0">Pending Invoice Payments</h5>
          </div>
          <div class="col-12 col-md-5">
            <div class="input-group">
              <span class="input-group-text bg-transparent border-end-0 text-muted">
                <Search :size="16" />
              </span>
              <input 
                type="text" 
                v-model="searchQuery" 
                class="form-control border-start-0 ps-1" 
                placeholder="Search by invoice, customer, registration..."
              />
            </div>
          </div>
        </div>
      </div>
      
      <div class="card-body p-0 mt-3">
        <div v-if="loading" class="text-center py-5">
          <div class="spinner-border text-danger" role="status"></div>
        </div>
        <div v-else-if="outstandingInvoices.length === 0" class="text-center py-5 text-muted small">
          <Check :size="40" class="mb-2 text-success" />
          <p class="m-0">Outstanding ledger cleared! No pending balances.</p>
        </div>
        <div v-else class="table-responsive">
          <table class="table table-hover mb-0">
            <thead>
              <tr class="text-uppercase small text-muted">
                <th class="ps-4">Invoice No</th>
                <th>Owner Details</th>
                <th>Reg No</th>
                <th>Bill Total</th>
                <th>Paid Amount</th>
                <th>Balance Due</th>
                <th class="text-end pe-4">Record Payment</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="inv in outstandingInvoices" :key="inv.id">
                <td class="ps-4 fw-bold text-danger">{{ inv.invoice_no }}</td>
                <td>
                  <div class="fw-bold">{{ inv.customer?.name }}</div>
                  <span class="text-muted small">{{ inv.customer?.mobile }}</span>
                </td>
                <td class="fw-bold font-monospace">{{ inv.vehicle_reg_no }}</td>
                <td class="font-monospace">{{ formatCurrency(inv.grand_total) }}</td>
                <td class="font-monospace text-success">{{ formatCurrency(inv.paid_amount) }}</td>
                <td class="font-monospace text-danger fw-bold fs-6">{{ formatCurrency(inv.balance_due) }}</td>
                <td class="text-end pe-4">
                  <button class="btn btn-sm btn-danger px-3 rounded-2" @click="openPaymentModal(inv)">
                    Log Collection
                  </button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <!-- Log Payment Modal -->
    <div v-if="showPaymentModal" class="modal-backdrop bg-black bg-opacity-50 position-fixed top-0 start-0 w-100 h-100 z-3 d-flex align-items-center justify-content-center">
      <div class="card border-0 shadow-lg bg-glass w-100 m-3 animate-zoom-in" style="max-width: 450px;">
        <div class="card-header border-0 bg-transparent pt-4 px-4 d-flex justify-content-between align-items-center">
          <h5 class="fw-bold m-0">Record Payment Collection</h5>
          <button class="btn btn-sm btn-outline-secondary border-0 btn-icon rounded-circle" @click="showPaymentModal = false">
            <X :size="18" />
          </button>
        </div>
        <form @submit.prevent="savePayment">
          <div class="card-body px-4 py-3" v-if="selectedInvoice">
            <div class="mb-3 small bg-light p-3 rounded">
              <div class="d-flex justify-content-between">
                <span>Invoice Number:</span>
                <strong class="font-monospace text-danger">{{ selectedInvoice.invoice_no }}</strong>
              </div>
              <div class="d-flex justify-content-between mt-1">
                <span>Registration No:</span>
                <strong class="font-monospace">{{ selectedInvoice.vehicle_reg_no }}</strong>
              </div>
              <div class="d-flex justify-content-between mt-1 pt-1 border-top">
                <span>Total Balance Due:</span>
                <strong class="text-danger">{{ formatCurrency(selectedInvoice.balance_due) }}</strong>
              </div>
            </div>
            
            <div class="mb-3">
              <label class="form-label small fw-bold text-muted uppercase">Collection Amount (₹)</label>
              <div class="input-group">
                <span class="input-group-text bg-transparent text-muted">₹</span>
                <input 
                  type="number" 
                  step="0.01" 
                  v-model="formPayment.amount" 
                  class="form-control font-monospace fw-bold fs-5 text-danger" 
                  :max="parseFloat(selectedInvoice.balance_due)"
                  required 
                />
              </div>
            </div>

            <div class="mb-3">
              <label class="form-label small fw-bold text-muted uppercase">Payment Channel</label>
              <select v-model="formPayment.payment_mode" class="form-select" required>
                <option value="Cash">💵 Cash</option>
                <option value="UPI">📱 UPI / PhonePay / GPay</option>
                <option value="Card">💳 Credit / Debit Card</option>
                <option value="NetBanking">🏦 Bank NEFT Transfer</option>
              </select>
            </div>
          </div>
          <div class="card-footer border-0 bg-transparent px-4 pb-4 pt-0 d-flex justify-content-end gap-2">
            <button type="button" class="btn btn-outline-secondary px-3" @click="showPaymentModal = false">Cancel</button>
            <button type="submit" class="btn btn-danger px-4" style="background-color: #d71920; border-color: #d71920;">Submit Collection</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<style scoped>
.bg-glass {
  background-color: var(--bg-card);
  backdrop-filter: blur(10px);
  border: 1px solid var(--border-color) !important;
}

.btn-icon {
  width: 32px;
  height: 32px;
  border-radius: 6px;
  padding: 0;
  display: inline-flex;
  align-items: center;
  justify-content: center;
}

.animate-zoom-in {
  animation: zoomIn 0.2s cubic-bezier(0.16, 1, 0.3, 1);
}

@keyframes zoomIn {
  from {
    opacity: 0;
    transform: scale(0.95);
  }
  to {
    opacity: 1;
    transform: scale(1);
  }
}
</style>

// resources/js/pages/Payments.tsx
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { 
  Search, X, CheckCircle2, DollarSign
} from 'lucide-react';

export default function Payments() {
  const [invoices, setInvoices] = useState<any[]>([]);
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState('');
  const [rangeFilter, setRangeFilter] = useState('month'); // today, week, month, custom
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [loading, setLoading] = useState(true);

  // Payment Recording Modal States
  const [showPaymentModal, setShowPaymentModal] = useState(false);
  const [selectedInvoice, setSelectedInvoice] = useState<any>(null);
  const [payAmount, setPayAmount] = useState('');
  const [payMode, setPayMode] = useState('Cash');
  const [paymentError, setPaymentError] = useState('');

  const fetchInvoices = async () => {
    try {
      setLoading(true);
      let url = `/api/invoices?search=${search}&status=${statusFilter}&range=${rangeFilter}`;
      if (rangeFilter === 'custom') {
        url += `&start_date=${startDate}&end_date=${endDate}`;
      }
      const res = await axios.get(url);
      setInvoices(res.data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    const delayDebounceFn = setTimeout(() => {
      fetchInvoices();
    }, 300);
    return () => clearTimeout(delayDebounceFn);
  }, [search, statusFilter, rangeFilter, startDate, endDate]);

  const openPaymentModal = (inv: any) => {
    setSelectedInvoice(inv);
    setPayAmount(String(inv.balance_due || ''));
    setPayMode('Cash');
    setPaymentError('');
    setShowPaymentModal(true);
  };

  const handleRecordPayment = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!payAmount || parseFloat(payAmount) <= 0) {
      setPaymentError('Please enter a valid amount.');
      return;
    }
    setPaymentError('');

    try {
      await axios.post(`/api/invoices/${selectedInvoice.invoice_no}/payment`, {
        amount: parseFloat(payAmount),
        payment_mode: payMode
      });
      setShowPaymentModal(false);
      fetchInvoices();
    } catch (err: any) {
      setPaymentError(err.response?.data?.error || 'Failed to record transaction.');
    }
  };

  const payStatusColors: any = {
    'Paid': 'bg-emerald-500/10 text-emerald-500 border-emerald-500/20',
    'Partially Paid': 'bg-amber-500/10 text-amber-400 border-amber-500/20',
    'Pending': 'bg-red-500/10 text-red-500 border-red-500/20',
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 space-y-6">
      {/* Controls & Filters */}
      <div className="flex flex-col xl:flex-row items-stretch xl:items-center justify-between gap-4">
        {/* Search */}
        <div className="relative flex-1">
          <span className="absolute inset-y-0 left-0 pl-3 flex items-center text-slate-500">
            <Search size={18} />
          </span>
          <input
            type="text"
            placeholder="Search invoice number, customer, registration, mobile..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full pl-10 pr-4 py-2.5 bg-slate-950 border border-slate-800 focus:border-red-600 rounded-xl outline-none text-slate-200 text-sm transition-all"
          />
        </div>

        {/* Date and Status Filters */}
        <div className="flex flex-wrap items-center gap-3">
          {/* Status */}
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="px-3 py-2 bg-slate-950 border border-slate-800 focus:border-red-600 rounded-xl outline-none text-slate-300 text-xs font-semibold"
          >
            <option value="">All Payments</option>
            <option value="Paid">Paid</option>
            <option value="Partially Paid">Partially Paid</option>
            <option value="Pending">Pending</option>
          </select>

          {/* Time range */}
          <select
            value={rangeFilter}
            onChange={(e) => setRangeFilter(e.target.value)}
            className="px-3 py-2 bg-slate-950 border border-slate-800 focus:border-red-600 rounded-xl outline-none text-slate-300 text-xs font-semibold"
          >
            <option value="today">Today</option>
            <option value="week">This Week</option>
            <option value="month">This Month</option>
            <option value="custom">Custom Date Range</option>
          </select>

          {/* Custom Date Inputs */}
          {rangeFilter === 'custom' && (
            <div className="flex items-center gap-2">
              <input
                type="date"
                value={startDate}
                onChange={(e) => setStartDate(e.target.value)}
                className="px-2 py-1.5 bg-slate-950 border border-slate-800 rounded-xl text-slate-200 text-xs font-mono outline-none"
              />
              <span className="text-slate-500 text-xs">to</span>
              <input
                type="date"
                value={endDate}
                onChange={(e) => setEndDate(e.target.value)}
                className="px-2 py-1.5 bg-slate-950 border border-slate-800 rounded-xl text-slate-200 text-xs font-mono outline-none"
              />
            </div>
          )}
        </div>
      </div>

      {/* Table */}
      {loading ? (
        <div className="flex items-center justify-center h-48">
          <div className="w-6 h-6 border-2 border-red-600 border-t-transparent rounded-full animate-spin"></div>
        </div>
      ) : (
        <div className="overflow-x-auto border border-slate-800 rounded-xl">
          <table className="w-full border-collapse text-left">
            <thead>
              <tr className="bg-slate-950 text-slate-400 border-b border-slate-800 text-xs font-bold uppercase tracking-wider">
                <th className="p-4">Invoice No.</th>
                <th className="p-4">Date</th>
                <th className="p-4">Customer & Vehicle</th>
                <th className="p-4 text-right">Invoice Sum</th>
                <th className="p-4 text-right">Balance Due</th>
                <th className="p-4">Status</th>
                <th className="p-4 text-right">Payment Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800 text-sm text-slate-300">
              {invoices.map((inv) => (
                <tr key={inv.invoice_no} className="hover:bg-slate-800/40 transition-colors">
                  <td className="p-4 font-mono font-bold text-slate-100">{inv.invoice_no}</td>
                  <td className="p-4 font-mono text-xs text-slate-400">{inv.date}</td>
                  <td className="p-4">
                    <div>
                      <div className="font-semibold text-slate-200">{inv.customer_name}</div>
                      <div className="text-xs text-slate-500 font-mono mt-0.5">{inv.vehicle_reg_no} ({inv.vehicle_make} {inv.vehicle_model})</div>
                    </div>
                  </td>
                  <td className="p-4 text-right font-mono font-bold">₹{inv.grand_total.toFixed(2)}</td>
                  <td className="p-4 text-right font-mono font-bold text-red-500">₹{inv.balance_due.toFixed(2)}</td>
                  <td className="p-4">
                    <span className={`text-[10px] px-2 py-0.5 font-bold uppercase rounded-md border ${payStatusColors[inv.payment_status]}`}>
                      {inv.payment_status}
                    </span>
                  </td>
                  <td className="p-4 text-right">
                    {inv.balance_due > 0 ? (
                      <button
                        onClick={() => openPaymentModal(inv)}
                        className="px-3 py-1.5 bg-red-600 hover:bg-red-700 text-white rounded-lg text-xs font-semibold transition-all shadow-md cursor-pointer"
                      >
                        Record Payment
                      </button>
                    ) : (
                      <span className="text-xs text-emerald-500 font-bold flex items-center justify-end gap-1"><CheckCircle2 size={12} /> Paid</span>
                    )}
                  </td>
                </tr>
              ))}
              {invoices.length === 0 && (
                <tr>
                  <td colSpan={7} className="p-8 text-center text-slate-500">
                    No invoice records found matching current criteria.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      )}

      {/* Record Payment Dialog */}
      {showPaymentModal && (
        <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="w-full max-w-md bg-slate-900 border border-slate-800 rounded-2xl shadow-2xl overflow-hidden">
            <div className="h-16 border-b border-slate-800 px-6 flex items-center justify-between bg-slate-950">
              <h4 className="font-bold text-slate-50 flex items-center gap-2">
                <DollarSign size={16} className="text-red-500" />
                <span>Process Payment</span>
              </h4>
              <button onClick={() => setShowPaymentModal(false)} className="text-slate-400 hover:text-slate-100">
                <X size={20} />
              </button>
            </div>

            <form onSubmit={handleRecordPayment} className="p-6 space-y-4">
              {paymentError && (
                <div className="p-3.5 bg-red-500/10 border border-red-500/20 text-red-500 rounded-xl text-xs">
                  {paymentError}
                </div>
              )}

              <div className="bg-slate-950 border border-slate-850 p-4 rounded-xl space-y-1 text-xs text-slate-400">
                <div>Invoice Number: <strong className="text-slate-200 font-mono">{selectedInvoice.invoice_no}</strong></div>
                <div>Customer Name: <strong className="text-slate-200">{selectedInvoice.customer_name}</strong></div>
                <div>Total Bill: <strong className="text-slate-200 font-mono">₹{selectedInvoice.grand_total.toFixed(2)}</strong></div>
                <div>Balance Due: <strong className="text-red-500 font-mono">₹{selectedInvoice.balance_due.toFixed(2)}</strong></div>
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Payment Amount (₹)</label>
                <input
                  type="number"
                  step="0.01"
                  required
                  max={selectedInvoice.balance_due}
                  value={payAmount}
                  onChange={(e) => setPayAmount(e.target.value)}
                  className="w-full px-3 py-2 bg-slate-950 border border-slate-800 focus:border-red-600 rounded-xl text-slate-200 text-sm outline-none font-mono"
                />
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Payment Mode</label>
                <select
                  value={payMode}
                  onChange={(e) => setPayMode(e.target.value)}
                  className="w-full px-3 py-2 bg-slate-950 border border-slate-800 focus:border-red-600 rounded-xl text-slate-200 text-sm outline-none font-semibold"
                >
                  <option value="Cash">Cash</option>
                  <option value="UPI">UPI (Google Pay, PhonePe, Paytm)</option>
                  <option value="Bank Transfer">Bank Transfer (IMPS, NEFT)</option>
                  <option value="Card">Credit/Debit Card</option>
                  <option value="Cheque">Cheque</option>
                </select>
              </div>

              <div className="pt-4 border-t border-slate-800 flex items-center justify-end gap-3 bg-slate-950 -mx-6 -mb-6 p-6">
                <button
                  type="button"
                  onClick={() => setShowPaymentModal(false)}
                  className="px-4 py-2 border border-slate-800 hover:bg-slate-800 text-slate-300 rounded-xl text-sm transition-all"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-5 py-2.5 bg-red-600 hover:bg-red-700 text-white rounded-xl text-sm font-semibold transition-all shadow-lg shadow-red-600/15 cursor-pointer"
                >
                  Submit Payment
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
