// frontend/src/pages/Vehicles.tsx
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { 
  Car, Search, Plus, Edit2, Trash2, X, Sparkles, Shield, User, Gauge, Eye
} from 'lucide-react';

export default function Vehicles() {
  const [vehicles, setVehicles] = useState<any[]>([]);
  const [customers, setCustomers] = useState<any[]>([]);
  const [search, setSearch] = useState('');
  const [loading, setLoading] = useState(true);
  const [showModal, setShowModal] = useState(false);
  const [currentVehicle, setCurrentVehicle] = useState<any>(null);
  const [selectedVehicleReg, setSelectedVehicleReg] = useState<string | null>(null);
  const [historyData, setHistoryData] = useState<any>(null);
  const [historyLoading, setHistoryLoading] = useState(false);

  // Form states
  const [registrationNo, setRegistrationNo] = useState('');
  const [customerId, setCustomerId] = useState('');
  const [make, setMake] = useState('');
  const [model, setModel] = useState('');
  const [year, setYear] = useState('');
  const [fuelType, setFuelType] = useState('Petrol');
  const [chassisNo, setChassisNo] = useState('');
  const [engineNo, setEngineNo] = useState('');
  const [color, setColor] = useState('');
  const [insuranceCompany, setInsuranceCompany] = useState('');
  const [policyNumber, setPolicyNumber] = useState('');
  const [policyExpiry, setPolicyExpiry] = useState('');
  const [currentKm, setCurrentKm] = useState('');
  const [formError, setFormError] = useState('');

  const fetchVehicles = async () => {
    try {
      setLoading(true);
      const res = await axios.get(`/api/vehicles?search=${search}`);
      setVehicles(res.data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const fetchCustomers = async () => {
    try {
      const res = await axios.get('/api/customers');
      setCustomers(res.data);
    } catch (err) {
      console.error(err);
    }
  };

  useEffect(() => {
    const delayDebounceFn = setTimeout(() => {
      fetchVehicles();
    }, 300);
    return () => clearTimeout(delayDebounceFn);
  }, [search]);

  useEffect(() => {
    fetchCustomers();
  }, []);

  const loadHistory = async (reg: string) => {
    try {
      setHistoryLoading(true);
      setSelectedVehicleReg(reg);
      const res = await axios.get(`/api/vehicles/${encodeURIComponent(reg)}`);
      setHistoryData(res.data);
    } catch (err) {
      console.error(err);
    } finally {
      setHistoryLoading(false);
    }
  };

  const openAddModal = () => {
    setCurrentVehicle(null);
    setRegistrationNo('');
    setCustomerId('');
    setMake('');
    setModel('');
    setYear('');
    setFuelType('Petrol');
    setChassisNo('');
    setEngineNo('');
    setColor('');
    setInsuranceCompany('');
    setPolicyNumber('');
    setPolicyExpiry('');
    setCurrentKm('');
    setFormError('');
    setShowModal(true);
  };

  const openEditModal = (veh: any) => {
    setCurrentVehicle(veh);
    setRegistrationNo(veh.registration_no);
    setCustomerId(veh.customer_id || '');
    setMake(veh.make || '');
    setModel(veh.model || '');
    setYear(veh.year ? String(veh.year) : '');
    setFuelType(veh.fuel_type || 'Petrol');
    setChassisNo(veh.chassis_no || '');
    setEngineNo(veh.engine_no || '');
    setColor(veh.color || '');
    setInsuranceCompany(veh.insurance_company || '');
    setPolicyNumber(veh.policy_number || '');
    setPolicyExpiry(veh.policy_expiry || '');
    setCurrentKm(veh.current_km ? String(veh.current_km) : '');
    setFormError('');
    setShowModal(true);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!registrationNo || !customerId) {
      setFormError('Registration Number and Customer assignment are required.');
      return;
    }
    setFormError('');

    const payload = {
      registration_no: registrationNo, customer_id: parseInt(customerId),
      make, model, year: year ? parseInt(year) : null, fuel_type: fuelType,
      chassis_no: chassisNo, engine_no: engineNo, color,
      insurance_company: insuranceCompany, policy_number: policyNumber,
      policy_expiry: policyExpiry, current_km: currentKm ? parseInt(currentKm) : 0
    };

    try {
      if (currentVehicle) {
        await axios.put(`/api/vehicles/${encodeURIComponent(currentVehicle.registration_no)}`, payload);
      } else {
        await axios.post('/api/vehicles', payload);
      }
      setShowModal(false);
      fetchVehicles();
      if (selectedVehicleReg === registrationNo) {
        loadHistory(registrationNo);
      }
    } catch (err: any) {
      setFormError(err.response?.data?.error || 'Save failed. Verify unique registration number.');
    }
  };

  const handleDelete = async (reg: string) => {
    if (!window.confirm('Delete vehicle record? Links to past service history will be cleared.')) return;
    try {
      await axios.delete(`/api/vehicles/${encodeURIComponent(reg)}`);
      if (selectedVehicleReg === reg) setSelectedVehicleReg(null);
      fetchVehicles();
    } catch (err) {
      console.error(err);
    }
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 items-start">
      {/* Left panel: List & Search */}
      <div className="lg:col-span-2 bg-slate-900 border border-slate-800 rounded-2xl p-6 space-y-6">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div className="relative flex-1 w-full">
            <span className="absolute inset-y-0 left-0 pl-3 flex items-center text-slate-500">
              <Search size={18} />
            </span>
            <input
              type="text"
              placeholder="Search by vehicle reg, make, client name, mobile..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full pl-10 pr-4 py-2.5 bg-slate-950 border border-slate-800 focus:border-red-600 rounded-xl outline-none text-slate-200 text-sm transition-all focus:ring-2 focus:ring-red-600/10"
            />
          </div>
          <button
            onClick={openAddModal}
            className="w-full sm:w-auto px-4 py-2.5 bg-red-600 hover:bg-red-700 text-white rounded-xl text-sm font-semibold transition-all flex items-center justify-center gap-2 cursor-pointer shadow-lg shadow-red-600/15"
          >
            <Plus size={16} />
            <span>Add Vehicle</span>
          </button>
        </div>

        {loading ? (
          <div className="flex items-center justify-center h-48">
            <div className="w-6 h-6 border-2 border-red-600 border-t-transparent rounded-full animate-spin"></div>
          </div>
        ) : (
          <div className="overflow-x-auto border border-slate-800 rounded-xl">
            <table className="w-full border-collapse text-left">
              <thead>
                <tr className="bg-slate-950 text-slate-400 border-b border-slate-800 text-xs font-bold uppercase tracking-wider">
                  <th className="p-4">Reg No.</th>
                  <th className="p-4">Make / Model</th>
                  <th className="p-4">Customer Details</th>
                  <th className="p-4 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800 text-sm text-slate-300">
                {vehicles.map((veh) => (
                  <tr 
                    key={veh.registration_no} 
                    className={`hover:bg-slate-800/40 transition-colors cursor-pointer ${selectedVehicleReg === veh.registration_no ? 'bg-slate-800/60' : ''}`}
                    onClick={() => loadHistory(veh.registration_no)}
                  >
                    <td className="p-4 font-mono font-bold text-slate-100 uppercase">{veh.registration_no}</td>
                    <td className="p-4">{veh.make} {veh.model} {veh.year ? `(${veh.year})` : ''}</td>
                    <td className="p-4">
                      <div>
                        <div className="font-semibold text-slate-200">{veh.customer_name}</div>
                        <div className="text-xs text-slate-500 font-mono mt-0.5">{veh.customer_mobile}</div>
                      </div>
                    </td>
                    <td className="p-4 text-right" onClick={(e) => e.stopPropagation()}>
                      <div className="flex items-center justify-end gap-2">
                        <button 
                          onClick={() => loadHistory(veh.registration_no)}
                          className="p-2 bg-slate-950 border border-slate-800 hover:border-blue-500 hover:text-blue-400 text-slate-400 rounded-lg transition-all"
                        >
                          <Eye size={14} />
                        </button>
                        <button 
                          onClick={() => openEditModal(veh)}
                          className="p-2 bg-slate-950 border border-slate-800 hover:border-red-600 hover:text-red-500 text-slate-400 rounded-lg transition-all"
                        >
                          <Edit2 size={14} />
                        </button>
                        <button 
                          onClick={() => handleDelete(veh.registration_no)}
                          className="p-2 bg-slate-950 border border-slate-800 hover:border-red-600 hover:text-red-500 text-slate-400 rounded-lg transition-all"
                        >
                          <Trash2 size={14} />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
                {vehicles.length === 0 && (
                  <tr>
                    <td colSpan={4} className="p-8 text-center text-slate-500">
                      No vehicle records found.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Right panel: Timeline service history */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6">
        <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-4">VEHICLE REPAIR LOG & HISTORY</h3>
        
        {!selectedVehicleReg ? (
          <div className="h-64 border border-dashed border-slate-800 rounded-xl flex flex-col items-center justify-center text-slate-500 p-6 text-center">
            <Car size={32} className="mb-2 text-slate-700" />
            <span className="text-sm">Click a vehicle row or details eye to load service history.</span>
          </div>
        ) : historyLoading ? (
          <div className="flex items-center justify-center h-64">
            <div className="w-6 h-6 border-2 border-red-600 border-t-transparent rounded-full animate-spin"></div>
          </div>
        ) : (
          <div className="space-y-6">
            {/* Header info */}
            <div className="pb-4 border-b border-slate-800">
              <span className="font-mono font-black text-slate-50 uppercase text-lg">{historyData?.vehicle?.registration_no}</span>
              <h4 className="text-sm font-bold text-red-500 mt-1">{historyData?.vehicle?.make} {historyData?.vehicle?.model}</h4>
              
              <div className="mt-4 grid grid-cols-2 gap-3 text-xs text-slate-300">
                <div className="flex items-center gap-1.5"><User size={12} className="text-slate-500" /><span className="truncate">{historyData?.vehicle?.customer_name}</span></div>
                <div className="flex items-center gap-1.5"><Gauge size={12} className="text-slate-500" /><span className="font-mono">{historyData?.vehicle?.current_km?.toLocaleString()} KMS</span></div>
                {historyData?.vehicle?.engine_no && <div className="col-span-2 text-[10px] text-slate-400 font-mono">Engine No: {historyData?.vehicle?.engine_no}</div>}
                {historyData?.vehicle?.chassis_no && <div className="col-span-2 text-[10px] text-slate-400 font-mono">VIN/Chassis: {historyData?.vehicle?.chassis_no}</div>}
              </div>
            </div>

            {/* Timeline */}
            <div>
              <h5 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-4">SERVICE HISTORY TIMELINE</h5>
              <div className="relative border-l border-slate-800 pl-4 ml-2 space-y-6 text-xs">
                {historyData?.invoices?.map((inv: any) => {
                  const items = JSON.parse(inv.items || '[]');
                  return (
                    <div key={inv.invoice_no} className="relative">
                      {/* Timeline dot */}
                      <span className="absolute -left-[21px] top-0.5 w-3.5 h-3.5 rounded-full bg-red-600 border border-slate-900 flex items-center justify-center font-bold text-[7px] text-white">I</span>
                      
                      <div className="space-y-1">
                        <div className="flex items-center justify-between">
                          <span className="font-bold text-slate-200">{inv.invoice_no}</span>
                          <span className="text-[10px] text-slate-500 font-mono">{inv.date}</span>
                        </div>
                        <p className="text-slate-400 font-semibold">{inv.service_type || 'General Repair'}</p>
                        <div className="text-[10px] text-slate-500 space-y-0.5">
                          {items.slice(0, 3).map((it: any, index: number) => (
                            <div key={index} className="truncate">• {it.description} (Qty: {it.qty})</div>
                          ))}
                          {items.length > 3 && <div>and {items.length - 3} more items...</div>}
                        </div>
                        <div className="pt-1 flex items-center justify-between font-mono font-bold text-[10px] text-red-400">
                          <span>Total Bill:</span>
                          <span>₹{inv.grand_total.toFixed(2)}</span>
                        </div>
                      </div>
                    </div>
                  );
                })}

                {historyData?.jobCards?.map((jc: any) => (
                  <div key={jc.job_card_no} className="relative">
                    <span className="absolute -left-[21px] top-0.5 w-3.5 h-3.5 rounded-full bg-blue-600 border border-slate-900 flex items-center justify-center font-bold text-[7px] text-white">J</span>
                    
                    <div className="space-y-1">
                      <div className="flex items-center justify-between">
                        <span className="font-bold text-slate-300">{jc.job_card_no}</span>
                        <span className="text-[10px] text-slate-500 font-mono">{jc.date}</span>
                      </div>
                      <p className="text-slate-400 font-semibold">Job Card Created</p>
                      <div className="text-[10px] text-slate-500">
                        Status: <span className="font-bold text-slate-400 uppercase">{jc.status}</span>
                      </div>
                    </div>
                  </div>
                ))}

                {(!historyData?.invoices || historyData.invoices.length === 0) && 
                 (!historyData?.jobCards || historyData.jobCards.length === 0) && (
                  <p className="text-slate-500 py-4 text-center">No service history records found for this vehicle.</p>
                )}
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Add / Edit Modal */}
      {showModal && (
        <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="w-full max-w-xl bg-slate-900 border border-slate-800 rounded-2xl shadow-2xl overflow-hidden max-h-[90vh] flex flex-col">
            <div className="h-16 border-b border-slate-800 px-6 flex items-center justify-between bg-slate-950">
              <h4 className="font-bold text-slate-50 flex items-center gap-2">
                <Sparkles size={16} className="text-red-500" />
                <span>{currentVehicle ? 'Edit Vehicle Info' : 'Register New Vehicle'}</span>
              </h4>
              <button onClick={() => setShowModal(false)} className="text-slate-400 hover:text-slate-100">
                <X size={20} />
              </button>
            </div>

            <form onSubmit={handleSubmit} className="flex-1 overflow-y-auto p-6 space-y-4">
              {formError && (
                <div className="p-3.5 bg-red-500/10 border border-red-500/20 text-red-500 rounded-xl text-xs">
                  {formError}
                </div>
              )}

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Registration Number *</label>
                  <input
                    type="text"
                    required
                    disabled={!!currentVehicle} // Reg no is key
                    value={registrationNo}
                    onChange={(e) => setRegistrationNo(e.target.value)}
                    placeholder="GJ01AB1234"
                    className="w-full px-3 py-2 bg-slate-950 border border-slate-800 rounded-xl text-slate-200 text-sm focus:border-red-600 outline-none uppercase font-mono"
                  />
                </div>
                <div>
                  <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Assign Customer *</label>
                  <select
                    required
                    value={customerId}
                    onChange={(e) => setCustomerId(e.target.value)}
                    className="w-full px-3 py-2 bg-slate-950 border border-slate-800 rounded-xl text-slate-200 text-sm focus:border-red-600 outline-none"
                  >
                    <option value="">-- Select Customer --</option>
                    {customers.map((c) => (
                      <option key={c.id} value={c.id}>{c.name} ({c.mobile})</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Make / Brand</label>
                  <input
                    type="text"
                    value={make}
                    onChange={(e) => setMake(e.target.value)}
                    placeholder="Maruti Suzuki, Hyundai, Honda..."
                    className="w-full px-3 py-2 bg-slate-950 border border-slate-800 rounded-xl text-slate-200 text-sm focus:border-red-600 outline-none"
                  />
                </div>
                <div>
                  <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Model</label>
                  <input
                    type="text"
                    value={model}
                    onChange={(e) => setModel(e.target.value)}
                    placeholder="Swift, Creta, City..."
                    className="w-full px-3 py-2 bg-slate-950 border border-slate-800 rounded-xl text-slate-200 text-sm focus:border-red-600 outline-none"
                  />
                </div>
                <div>
                  <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Year</label>
                  <input
                    type="number"
                    value={year}
                    onChange={(e) => setYear(e.target.value)}
                    placeholder="2020"
                    className="w-full px-3 py-2 bg-slate-950 border border-slate-800 rounded-xl text-slate-200 text-sm focus:border-red-600 outline-none font-mono"
                  />
                </div>
                <div>
                  <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Fuel Type</label>
                  <select
                    value={fuelType}
                    onChange={(e) => setFuelType(e.target.value)}
                    className="w-full px-3 py-2 bg-slate-950 border border-slate-800 rounded-xl text-slate-200 text-sm focus:border-red-600 outline-none"
                  >
                    <option value="Petrol">Petrol</option>
                    <option value="Diesel">Diesel</option>
                    <option value="CNG">CNG</option>
                    <option value="EV">EV (Electric)</option>
                    <option value="Hybrid">Hybrid</option>
                  </select>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div>
                  <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Chassis Number (VIN)</label>
                  <input
                    type="text"
                    value={chassisNo}
                    onChange={(e) => setChassisNo(e.target.value)}
                    placeholder="17-digit chassis code"
                    className="w-full px-3 py-2 bg-slate-950 border border-slate-800 rounded-xl text-slate-200 text-sm focus:border-red-600 outline-none font-mono uppercase"
                  />
                </div>
                <div>
                  <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Engine Number</label>
                  <input
                    type="text"
                    value={engineNo}
                    onChange={(e) => setEngineNo(e.target.value)}
                    placeholder="Engine code"
                    className="w-full px-3 py-2 bg-slate-950 border border-slate-800 rounded-xl text-slate-200 text-sm focus:border-red-600 outline-none font-mono uppercase"
                  />
                </div>
                <div>
                  <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Color</label>
                  <input
                    type="text"
                    value={color}
                    onChange={(e) => setColor(e.target.value)}
                    placeholder="White, Silver..."
                    className="w-full px-3 py-2 bg-slate-950 border border-slate-800 rounded-xl text-slate-200 text-sm focus:border-red-600 outline-none"
                  />
                </div>
              </div>

              <div className="border-t border-slate-800 pt-4 space-y-4">
                <span className="text-xs font-bold text-red-500 uppercase flex items-center gap-1.5"><Shield size={14} /> Insurance Information</span>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div>
                    <label className="block text-[10px] font-semibold text-slate-400 uppercase tracking-wider mb-1.5">Insurance Co</label>
                    <input
                      type="text"
                      value={insuranceCompany}
                      onChange={(e) => setInsuranceCompany(e.target.value)}
                      placeholder="ICICI Lombard..."
                      className="w-full px-3 py-2 bg-slate-950 border border-slate-800 rounded-xl text-slate-200 text-sm focus:border-red-600 outline-none"
                    />
                  </div>
                  <div>
                    <label className="block text-[10px] font-semibold text-slate-400 uppercase tracking-wider mb-1.5">Policy Number</label>
                    <input
                      type="text"
                      value={policyNumber}
                      onChange={(e) => setPolicyNumber(e.target.value)}
                      placeholder="Policy No"
                      className="w-full px-3 py-2 bg-slate-950 border border-slate-800 rounded-xl text-slate-200 text-sm focus:border-red-600 outline-none font-mono"
                    />
                  </div>
                  <div>
                    <label className="block text-[10px] font-semibold text-slate-400 uppercase tracking-wider mb-1.5">Policy Expiry</label>
                    <input
                      type="date"
                      value={policyExpiry}
                      onChange={(e) => setPolicyExpiry(e.target.value)}
                      className="w-full px-3 py-2 bg-slate-950 border border-slate-800 rounded-xl text-slate-200 text-sm focus:border-red-600 outline-none font-mono"
                    />
                  </div>
                </div>
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Current KM Reading</label>
                <input
                  type="number"
                  value={currentKm}
                  onChange={(e) => setCurrentKm(e.target.value)}
                  placeholder="34500"
                  className="w-full px-3 py-2 bg-slate-950 border border-slate-800 rounded-xl text-slate-200 text-sm focus:border-red-600 outline-none font-mono"
                />
              </div>

              <div className="pt-4 border-t border-slate-800 flex items-center justify-end gap-3 bg-slate-950 -mx-6 -mb-6 p-6">
                <button
                  type="button"
                  onClick={() => setShowModal(false)}
                  className="px-4 py-2 border border-slate-800 hover:bg-slate-800 text-slate-300 rounded-xl text-sm transition-all"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-5 py-2.5 bg-red-600 hover:bg-red-700 text-white rounded-xl text-sm font-semibold transition-all shadow-lg shadow-red-600/15 cursor-pointer"
                >
                  Save Record
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}

// resources/js/views/Vehicles.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import axios from 'axios'
import { 
  Car, Search, PlusCircle, Edit, History, 
  User, CheckSquare, ShieldCheck, ChevronRight, X
} from 'lucide-vue-next'

const vehicles = ref<any[]>([])
const customersList = ref<any[]>([])
const searchQuery = ref('')
const loading = ref(false)
const historyLoading = ref(false)
const selectedVehicle = ref<any | null>(null)
const vehicleHistory = ref<any[]>([])
const activeTab = ref('jobcards')

// Form Modal State
const showModal = ref(false)
const editMode = ref(false)
const formVehicle = ref({
  registration_no: '',
  customer_id: null as number | null,
  make: '',
  model: '',
  year: new Date().getFullYear(),
  fuel_type: 'PETROL',
  engine_no: '',
  chassis_no: '',
  color: '',
  insurance_company: '',
  policy_number: '',
  policy_expiry: '',
  current_km: 0
})

const fetchVehicles = async () => {
  loading.value = true
  try {
    const res = await axios.get('/api/vehicles', {
      params: { search: searchQuery.value }
    })
    vehicles.value = res.data
  } catch (err) {
    console.error('Failed to load vehicles', err)
  } finally {
    loading.value = false
  }
}

const fetchCustomers = async () => {
  try {
    const res = await axios.get('/api/customers')
    customersList.value = res.data
  } catch (err) {
    console.error('Failed to load customers', err)
  }
}

const openNewModal = () => {
  editMode.value = false
  formVehicle.value = {
    registration_no: '',
    customer_id: customersList.value[0]?.id || null,
    make: '',
    model: '',
    year: new Date().getFullYear(),
    fuel_type: 'PETROL',
    engine_no: '',
    chassis_no: '',
    color: '',
    insurance_company: '',
    policy_number: '',
    policy_expiry: '',
    current_km: 0
  }
  showModal.value = true
}

const openEditModal = (vehicle: any) => {
  editMode.value = true
  formVehicle.value = { ...vehicle }
  showModal.value = true
}

const saveVehicle = async () => {
  try {
    if (editMode.value) {
      await axios.put(`/api/vehicles/${formVehicle.value.registration_no}`, formVehicle.value)
    } else {
      await axios.post('/api/vehicles', formVehicle.value)
    }
    showModal.value = false
    fetchVehicles()
  } catch (err: any) {
    alert(err.response?.data?.error || 'Failed to save vehicle details.')
  }
}

const selectVehicle = async (vehicle: any) => {
  selectedVehicle.value = vehicle
  vehicleHistory.value = []
  historyLoading.value = true
  activeTab.value = 'jobcards'
  try {
    const res = await axios.get(`/api/vehicles/${vehicle.registration_no}/history`)
    vehicleHistory.value = res.data
  } catch (err) {
    console.error('Failed to load vehicle history', err)
  } finally {
    historyLoading.value = false
  }
}

onMounted(() => {
  fetchVehicles()
  fetchCustomers()
})
</script>

<template>
  <div class="vehicles-container animate-fade-in">
    <!-- Header -->
    <div class="d-flex justify-content-between align-items-center mb-4">
      <div>
        <h3 class="fw-bold mb-1">Vehicle Database</h3>
        <p class="text-muted small mb-0">Track vehicles, owners, technical specs, insurance, and service histories.</p>
      </div>
      <button class="btn btn-danger d-flex align-items-center gap-2 px-3 rounded-3" @click="openNewModal">
        <PlusCircle :size="16" />
        <span>Add Vehicle</span>
      </button>
    </div>

    <!-- Search & List Layout -->
    <div class="row g-4">
      <div :class="selectedVehicle ? 'col-12 col-lg-7' : 'col-12'">
        <div class="card border-0 shadow-sm bg-glass h-100">
          <div class="card-header border-0 bg-transparent pt-4 px-4 pb-0">
            <div class="input-group">
              <span class="input-group-text bg-transparent border-end-0 text-muted">
                <Search :size="16" />
              </span>
              <input 
                type="text" 
                v-model="searchQuery" 
                class="form-control border-start-0 ps-1" 
                placeholder="Search by registration number, make, model, owner..."
                @input="fetchVehicles"
              />
            </div>
          </div>
          <div class="card-body p-0 mt-3">
            <div v-if="loading" class="text-center py-5">
              <div class="spinner-border text-danger" role="status"></div>
            </div>
            <div v-else-if="vehicles.length === 0" class="text-center py-5 text-muted small">
              <Car :size="40" class="mb-2 text-muted" />
              <p class="m-0">No matching vehicle records found.</p>
            </div>
            <div v-else class="table-responsive">
              <table class="table table-hover mb-0">
                <thead>
                  <tr class="text-uppercase small text-muted">
                    <th class="ps-4">Registration No</th>
                    <th>Vehicle Model</th>
                    <th>Current Odo</th>
                    <th>Owner Name</th>
                    <th class="text-end pe-4">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <tr 
                    v-for="v in vehicles" 
                    :key="v.registration_no" 
                    class="cursor-pointer"
                    :class="{'table-active-danger': selectedVehicle?.registration_no === v.registration_no}"
                    @click="selectVehicle(v)"
                  >
                    <td class="ps-4 font-monospace fw-bold text-danger">
                      {{ v.registration_no }}
                    </td>
                    <td>
                      <div class="fw-bold">{{ v.make }} {{ v.model }}</div>
                      <span class="text-muted small">{{ v.fuel_type }} | {{ v.color }}</span>
                    </td>
                    <td>{{ v.current_km }} km</td>
                    <td>{{ v.customer?.name || 'Unknown' }}</td>
                    <td class="text-end pe-4" @click.stop>
                      <button class="btn btn-sm btn-outline-secondary me-2 btn-icon" @click="openEditModal(v)" title="Edit">
                        <Edit :size="14" />
                      </button>
                      <button class="btn btn-sm btn-dark btn-icon" @click="selectVehicle(v)">
                        <ChevronRight :size="14" />
                      </button>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>

      <!-- Vehicle Detail Sidebar Drawer -->
      <div v-if="selectedVehicle" class="col-12 col-lg-5 animate-slide-in">
        <div class="card border-0 shadow-sm bg-glass h-100">
          <div class="card-header border-0 bg-transparent pt-4 px-4 d-flex justify-content-between align-items-start">
            <div>
              <span class="badge bg-danger bg-opacity-10 text-danger font-monospace fw-bold px-2 py-1 mb-2">{{ selectedVehicle.registration_no }}</span>
              <h4 class="fw-bold m-0">{{ selectedVehicle.make }} {{ selectedVehicle.model }}</h4>
            </div>
            <button class="btn btn-sm btn-outline-secondary border-0 btn-icon rounded-circle" @click="selectedVehicle = null">
              <X :size="18" />
            </button>
          </div>

          <div class="card-body px-4">
            <!-- Owners & Tech Specs list -->
            <div class="d-flex flex-column gap-2 mb-4 bg-body bg-opacity-50 p-3 rounded-3 small">
              <div class="d-flex align-items-center gap-2">
                <User :size="14" class="text-danger" />
                <span>Owner: <strong>{{ selectedVehicle.customer?.name }}</strong> ({{ selectedVehicle.customer?.mobile }})</span>
              </div>
              <div class="row g-2 mt-1 pt-2 border-top border-secondary border-opacity-10">
                <div class="col-6">
                  <span class="text-muted d-block small-label">Fuel Type</span>
                  <span>{{ selectedVehicle.fuel_type }}</span>
                </div>
                <div class="col-6">
                  <span class="text-muted d-block small-label">Odometer</span>
                  <span>{{ selectedVehicle.current_km }} km</span>
                </div>
                <div class="col-6">
                  <span class="text-muted d-block small-label">Engine No</span>
                  <span class="font-monospace text-uppercase">{{ selectedVehicle.engine_no || 'N/A' }}</span>
                </div>
                <div class="col-6">
                  <span class="text-muted d-block small-label">Chassis No</span>
                  <span class="font-monospace text-uppercase">{{ selectedVehicle.chassis_no || 'N/A' }}</span>
                </div>
              </div>
            </div>

            <!-- Insurance Policy Block -->
            <div v-if="selectedVehicle.insurance_company" class="mb-4 bg-danger bg-opacity-5 border-start border-danger p-3 rounded-2 small">
              <div class="fw-bold mb-1 text-danger">Insurance Details</div>
              <div>Company: {{ selectedVehicle.insurance_company }}</div>
              <div>Policy: {{ selectedVehicle.policy_number }}</div>
              <div>Expiry: {{ selectedVehicle.policy_expiry || 'N/A' }}</div>
            </div>

            <!-- Tabs: Job Cards / Invoices -->
            <ul class="nav nav-tabs border-bottom mb-3" role="tablist">
              <li class="nav-item">
                <button 
                  class="nav-link bg-transparent border-0 fw-bold px-3 py-2 small"
                  :class="{'active-danger': activeTab === 'jobcards'}"
                  @click="activeTab = 'jobcards'"
                >
                  Job Cards
                </button>
              </li>
              <li class="nav-item">
                <button 
                  class="nav-link bg-transparent border-0 fw-bold px-3 py-2 small"
                  :class="{'active-danger': activeTab === 'invoices'}"
                  @click="activeTab = 'invoices'"
                >
                  Invoices
                </button>
              </li>
            </ul>

            <!-- Tab Content -->
            <div v-if="historyLoading" class="text-center py-4">
              <div class="spinner-border text-danger spinner-border-sm" role="status"></div>
            </div>
            <div v-else>
              <!-- Job Cards -->
              <div v-if="activeTab === 'jobcards'">
                <div v-if="!vehicleHistory.jobcards || vehicleHistory.jobcards.length === 0" class="text-center py-4 text-muted small">
                  No job card history on record.
                </div>
                <div v-else class="list-group list-group-flush">
                  <div 
                    v-for="jc in vehicleHistory.jobcards" 
                    :key="jc.id" 
                    class="list-group-item bg-transparent px-0 py-3 border-bottom d-flex justify-content-between align-items-center"
                  >
                    <div>
                      <div class="fw-bold font-monospace">{{ jc.job_card_no }}</div>
                      <span class="text-muted small">{{ jc.date }} | {{ jc.km_reading }} km</span>
                    </div>
                    <span class="badge" :class="{
                      'bg-secondary': jc.status === 'Open',
                      'bg-info text-dark': jc.status === 'Inspection',
                      'bg-warning text-dark': jc.status === 'In Progress' || jc.status === 'Waiting Parts',
                      'bg-success': jc.status === 'Completed' || jc.status === 'Delivered'
                    }">{{ jc.status }}</span>
                  </div>
                </div>
              </div>

              <!-- Invoices -->
              <div v-if="activeTab === 'invoices'">
                <div v-if="!vehicleHistory.invoices || vehicleHistory.invoices.length === 0" class="text-center py-4 text-muted small">
                  No invoice records found for this vehicle.
                </div>
                <div v-else class="list-group list-group-flush">
                  <div 
                    v-for="inv in vehicleHistory.invoices" 
                    :key="inv.id" 
                    class="list-group-item bg-transparent px-0 py-3 border-bottom d-flex justify-content-between align-items-center"
                  >
                    <div>
                      <div class="fw-bold font-monospace">{{ inv.invoice_no }}</div>
                      <span class="text-muted small">{{ inv.date }}</span>
                    </div>
                    <div class="text-end">
                      <div class="fw-bold">₹{{ parseFloat(inv.grand_total).toFixed(2) }}</div>
                      <span class="badge font-monospace" :class="{
                        'bg-success': inv.payment_status === 'Paid',
                        'bg-warning text-dark': inv.payment_status === 'Partially Paid',
                        'bg-danger': inv.payment_status === 'Pending'
                      }">{{ inv.payment_status }}</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Edit/New Vehicle Modal -->
    <div v-if="showModal" class="modal-backdrop bg-black bg-opacity-50 position-fixed top-0 start-0 w-100 h-100 z-3 d-flex align-items-center justify-content-center">
      <div class="card border-0 shadow-lg bg-glass w-100 m-3 animate-zoom-in" style="max-width: 650px;">
        <div class="card-header border-0 bg-transparent pt-4 px-4 d-flex justify-content-between align-items-center">
          <h5 class="fw-bold m-0">{{ editMode ? 'Edit Vehicle Details' : 'Add New Vehicle' }}</h5>
          <button class="btn btn-sm btn-outline-secondary border-0 btn-icon rounded-circle" @click="showModal = false">
            <X :size="18" />
          </button>
        </div>
        <form @submit.prevent="saveVehicle">
          <div class="card-body px-4 py-3" style="max-height: 70vh; overflow-y: auto;">
            <div class="row g-3">
              <div class="col-12 col-md-6">
                <label class="form-label small fw-bold text-muted uppercase">Registration No <span class="text-danger">*</span></label>
                <input 
                  type="text" 
                  v-model="formVehicle.registration_no" 
                  @input="formVehicle.registration_no = formVehicle.registration_no.toUpperCase().replace(/\s+/g, '')"
                  class="form-control font-monospace text-uppercase" 
                  placeholder="e.g. GJ01XX1234" 
                  required 
                  :disabled="editMode" 
                />
              </div>
              <div class="col-12 col-md-6">
                <label class="form-label small fw-bold text-muted uppercase">Owner / Customer <span class="text-danger">*</span></label>
                <select v-model="formVehicle.customer_id" class="form-select" required>
                  <option v-for="c in customersList" :key="c.id" :value="c.id">{{ c.name }} ({{ c.mobile }})</option>
                </select>
              </div>
              <div class="col-12 col-md-4">
                <label class="form-label small fw-bold text-muted uppercase">Make / Brand <span class="text-danger">*</span></label>
                <input type="text" v-model="formVehicle.make" class="form-control" placeholder="e.g. Maruti Suzuki" required />
              </div>
              <div class="col-12 col-md-4">
                <label class="form-label small fw-bold text-muted uppercase">Model Name <span class="text-danger">*</span></label>
                <input type="text" v-model="formVehicle.model" class="form-control" placeholder="e.g. Swift" required />
              </div>
              <div class="col-12 col-md-4">
                <label class="form-label small fw-bold text-muted uppercase">Fuel Type <span class="text-danger">*</span></label>
                <select v-model="formVehicle.fuel_type" class="form-select" required>
                  <option value="PETROL">PETROL</option>
                  <option value="DIESEL">DIESEL</option>
                  <option value="CNG">CNG</option>
                  <option value="ELECTRIC">ELECTRIC</option>
                </select>
              </div>
              <div class="col-12 col-md-4">
                <label class="form-label small fw-bold text-muted uppercase">Manufacturing Year</label>
                <input type="number" v-model="formVehicle.year" class="form-control" placeholder="2020" />
              </div>
              <div class="col-12 col-md-4">
                <label class="form-label small fw-bold text-muted uppercase">Current Odometer (KM)</label>
                <input type="number" v-model="formVehicle.current_km" class="form-control" placeholder="e.g. 52000" />
              </div>
              <div class="col-12 col-md-4">
                <label class="form-label small fw-bold text-muted uppercase">Body Color</label>
                <input type="text" v-model="formVehicle.color" class="form-control" placeholder="e.g. RED" />
              </div>
              <div class="col-12 col-md-6">
                <label class="form-label small fw-bold text-muted uppercase">Engine No (Optional)</label>
                <input type="text" v-model="formVehicle.engine_no" class="form-control font-monospace text-uppercase" placeholder="Optional Engine ID" />
              </div>
              <div class="col-12 col-md-6">
                <label class="form-label small fw-bold text-muted uppercase">Chassis No (Optional)</label>
                <input type="text" v-model="formVehicle.chassis_no" class="form-control font-monospace text-uppercase" placeholder="Optional Chassis ID" />
              </div>

              <!-- Insurance Details -->
              <div class="col-12 pt-2 border-top border-secondary border-opacity-10">
                <h6 class="fw-bold mb-3 text-muted uppercase small">Insurance Policy (Optional)</h6>
              </div>
              <div class="col-12 col-md-4">
                <label class="form-label small fw-bold text-muted uppercase">Insurance Co.</label>
                <input type="text" v-model="formVehicle.insurance_company" class="form-control" placeholder="e.g. HDFC Ergo" />
              </div>
              <div class="col-12 col-md-4">
                <label class="form-label small fw-bold text-muted uppercase">Policy Number</label>
                <input type="text" v-model="formVehicle.policy_number" class="form-control font-monospace" placeholder="e.g. PO102930219" />
              </div>
              <div class="col-12 col-md-4">
                <label class="form-label small fw-bold text-muted uppercase">Policy Expiry</label>
                <input type="date" v-model="formVehicle.policy_expiry" class="form-control" />
              </div>
            </div>
          </div>
          <div class="card-footer border-0 bg-transparent px-4 pb-4 pt-0 d-flex justify-content-end gap-2">
            <button type="button" class="btn btn-outline-secondary px-3" @click="showModal = false">Cancel</button>
            <button type="submit" class="btn btn-danger px-4" style="background-color: #d71920; border-color: #d71920;">Save Changes</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<style scoped>
.bg-glass {
  background-color: var(--bg-card);
  backdrop-filter: blur(10px);
  border: 1px solid var(--border-color) !important;
}

.cursor-pointer {
  cursor: pointer;
}

.table-active-danger {
  background-color: rgba(215, 25, 32, 0.08) !important;
  border-left: 3px solid #d71920;
}

.btn-icon {
  width: 32px;
  height: 32px;
  border-radius: 6px;
  padding: 0;
  display: inline-flex;
  align-items: center;
  justify-content: center;
}

.small-label {
  font-size: 10px;
  font-weight: 700;
  text-transform: uppercase;
}

.nav-link {
  color: var(--text-muted);
}

.active-danger {
  color: #d71920 !important;
  border-bottom: 2px solid #d71920 !important;
}

.animate-slide-in {
  animation: slideIn 0.3s ease-out;
}

@keyframes slideIn {
  from {
    opacity: 0;
    transform: translateX(20px);
  }
  to {
    opacity: 1;
    transform: translateX(0);
  }
}

.animate-zoom-in {
  animation: zoomIn 0.2s cubic-bezier(0.16, 1, 0.3, 1);
}

@keyframes zoomIn {
  from {
    opacity: 0;
    transform: scale(0.95);
  }
  to {
    opacity: 1;
    transform: scale(1);
  }
}
</style>
