// resources/js/views/Register.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth'
import axios from 'axios'
import { KeyRound, User as UserIcon, Shield, Mail, Sparkles } from 'lucide-vue-next'

const authStore = useAuthStore()
const router = useRouter()

const name = ref('')
const username = ref('')
const email = ref('')
const password = ref('')
const role = ref('advisor') // default

const error = ref('')
const success = ref('')
const loading = ref(false)

const handleRegister = async () => {
  if (!name.value || !username.value || !password.value) {
    error.value = 'Please fill out all mandatory fields.'
    return
  }

  loading.value = true
  error.value = ''
  success.value = ''

  try {
    await axios.post('/api/auth/register', {
      name: name.value,
      username: username.value,
      email: email.value || null,
      password: password.value,
      role: role.value
    })
    
    success.value = 'Staff registration successful! The new account is active.'
    
    // Reset form fields so admin can add another user
    name.value = ''
    username.value = ''
    email.value = ''
    password.value = ''
    role.value = 'advisor'

    setTimeout(() => {
      success.value = ''
    }, 4000)
    
  } catch (err: any) {
    console.error(err)
    error.value = err.response?.data?.error || 'Registration failed. Check if username is taken.'
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <div class="card register-card p-4 mx-3" style="width: 420px; border-radius: 16px;">
    <div class="text-center mb-4">
      <img src="/logo.png" alt="Trust Care" class="img-fluid mb-3" style="max-height: 60px; object-fit: contain;" />
      <h4 class="fw-bold mb-1">STAFF REGISTRATION</h4>
      <p class="text-muted small">Create Trust Care Workshop Account</p>
    </div>

    <div v-if="error" class="alert alert-danger py-2 px-3 small rounded-3 mb-3">
      {{ error }}
    </div>

    <div v-if="success" class="alert alert-success py-2 px-3 small rounded-3 mb-3">
      {{ success }}
    </div>

    <form @submit.prevent="handleRegister">
      <div class="mb-3">
        <label class="form-label small fw-bold text-muted uppercase">Full Name</label>
        <div class="input-group">
          <span class="input-group-text bg-transparent border-end-0 text-muted">
            <UserIcon :size="16" />
          </span>
          <input 
            type="text" 
            v-model="name" 
            class="form-control border-start-0" 
            placeholder="John Doe" 
            required 
          />
        </div>
      </div>

      <div class="mb-3">
        <label class="form-label small fw-bold text-muted uppercase">Username</label>
        <div class="input-group">
          <span class="input-group-text bg-transparent border-end-0 text-muted">
            <UserIcon :size="16" />
          </span>
          <input 
            type="text" 
            v-model="username" 
            class="form-control border-start-0" 
            placeholder="john_doe" 
            required 
          />
        </div>
      </div>

      <div class="mb-3">
        <label class="form-label small fw-bold text-muted uppercase">Email Address (Optional)</label>
        <div class="input-group">
          <span class="input-group-text bg-transparent border-end-0 text-muted">
            <Mail :size="16" />
          </span>
          <input 
            type="email" 
            v-model="email" 
            class="form-control border-start-0" 
            placeholder="john@trustcare.com" 
          />
        </div>
      </div>

      <div class="mb-3">
        <label class="form-label small fw-bold text-muted uppercase">Password</label>
        <div class="input-group">
          <span class="input-group-text bg-transparent border-end-0 text-muted">
            <KeyRound :size="16" />
          </span>
          <input 
            type="password" 
            v-model="password" 
            class="form-control border-start-0" 
            placeholder="••••••••" 
            required 
          />
        </div>
      </div>

      <div class="mb-4">
        <label class="form-label small fw-bold text-muted uppercase">Staff Role</label>
        <div class="input-group">
          <span class="input-group-text bg-transparent border-end-0 text-muted">
            <Shield :size="16" />
          </span>
          <select v-model="role" class="form-select border-start-0" required>
            <option value="advisor">Service Advisor</option>
            <option value="manager">Store Manager</option>
            <option value="admin">Admin</option>
          </select>
        </div>
      </div>

      <button 
        type="submit" 
        class="btn btn-danger w-full py-2.5 fw-bold text-white rounded-3 mb-3"
        style="background-color: #d71920; border-color: #d71920;"
        :disabled="loading"
      >
        <span v-if="loading" class="spinner-border spinner-border-sm me-2"></span>
        <span>Register Account</span>
      </button>

      <div class="text-center small">
        <router-link to="/settings" class="text-danger fw-bold text-decoration-none">← Go to Configurations</router-link>
      </div>
    </form>
  </div>
</template>

<style scoped>
.register-card {
  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.4);
  border: 1px solid rgba(255, 255, 255, 0.05);
}
.w-full {
  width: 100%;
}
</style>

// frontend/src/pages/Register.tsx
import React, { useState } from 'react';
import { useAuth } from '../App';
import { Link } from 'react-router-dom';
import axios from 'axios';
import { KeyRound, User, AlertCircle } from 'lucide-react';

export default function Register() {
  const { login } = useAuth();
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!username || !password || !confirmPassword) {
      setError('Please fill in all fields.');
      return;
    }
    if (password !== confirmPassword) {
      setError('Passwords do not match.');
      return;
    }
    setError('');
    setLoading(true);

    try {
      const res = await axios.post('/api/auth/register', { username, password });
      login(res.data.token, res.data.user);
    } catch (err: any) {
      setError(err.response?.data?.error || 'Failed to register. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-slate-950 px-4">
      <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-red-600/10 rounded-full blur-3xl pointer-events-none"></div>
      <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-red-800/5 rounded-full blur-3xl pointer-events-none"></div>

      <div className="w-full max-w-md bg-slate-900/80 backdrop-blur-xl border border-slate-800 p-8 rounded-2xl shadow-2xl relative">
        <div className="text-center mb-8">
          <div className="inline-flex w-14 h-14 rounded-2xl bg-red-600 items-center justify-center font-black text-2xl text-white shadow-xl shadow-red-600/20 mb-3">TC</div>
          <h2 className="text-2xl font-bold text-slate-50">Create Account</h2>
          <p className="text-slate-400 text-sm mt-1">TRUST CARE WORKSHOP MANAGEMENT SYSTEM</p>
        </div>

        {error && (
          <div className="mb-6 p-4 rounded-xl bg-red-500/10 border border-red-500/20 flex items-center gap-3 text-red-400 text-sm">
            <AlertCircle className="shrink-0" size={18} />
            <span>{error}</span>
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-5">
          <div>
            <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Username</label>
            <div className="relative">
              <span className="absolute inset-y-0 left-0 pl-3.5 flex items-center text-slate-500">
                <User size={18} />
              </span>
              <input
                type="text"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                placeholder="Choose a username"
                className="w-full pl-11 pr-4 py-3 bg-slate-950 border border-slate-800 focus:border-red-600 rounded-xl outline-none text-slate-200 text-sm transition-all focus:ring-2 focus:ring-red-600/20"
              />
            </div>
          </div>

          <div>
            <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Password</label>
            <div className="relative">
              <span className="absolute inset-y-0 left-0 pl-3.5 flex items-center text-slate-500">
                <KeyRound size={18} />
              </span>
              <input
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder="Choose a strong password"
                className="w-full pl-11 pr-4 py-3 bg-slate-950 border border-slate-800 focus:border-red-600 rounded-xl outline-none text-slate-200 text-sm transition-all focus:ring-2 focus:ring-red-600/20"
              />
            </div>
          </div>

          <div>
            <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Confirm Password</label>
            <div className="relative">
              <span className="absolute inset-y-0 left-0 pl-3.5 flex items-center text-slate-500">
                <KeyRound size={18} />
              </span>
              <input
                type="password"
                value={confirmPassword}
                onChange={(e) => setConfirmPassword(e.target.value)}
                placeholder="Re-enter password"
                className="w-full pl-11 pr-4 py-3 bg-slate-950 border border-slate-800 focus:border-red-600 rounded-xl outline-none text-slate-200 text-sm transition-all focus:ring-2 focus:ring-red-600/20"
              />
            </div>
          </div>

          <button
            type="submit"
            disabled={loading}
            className="w-full py-3.5 bg-red-600 hover:bg-red-700 disabled:bg-red-800/50 rounded-xl text-white font-bold text-sm tracking-wider shadow-lg shadow-red-600/10 hover:shadow-red-600/20 transition-all cursor-pointer flex items-center justify-center gap-2 mt-4"
          >
            {loading ? (
              <>
                <div className="w-4 h-4 rounded-full border-2 border-white border-t-transparent animate-spin"></div>
                <span>Creating Account...</span>
              </>
            ) : (
              <span>CREATE ACCOUNT</span>
            )}
          </button>
        </form>

        <div className="text-center mt-6">
          <p className="text-xs text-slate-500">
            Already have an account?{' '}
            <Link to="/login" className="text-red-500 hover:text-red-400 font-semibold transition-all">
              Sign In
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
}
